TS Assignment
rishikesh-dhanawade-emtec/devyani_repo pull request #5
Opened 2022-09-08 11:38 UTC by Devyani-Chaudhari

Completed Questions: Q1, Q2, Q3, Q6, Q7, Q8, Q9, Q11, Q12, Q13, Q14, Q15.
Remaining Questions : Q4, Q5, Q10

2022-09-13 09:28 UTC, rishikesh-dhanawade-emtec commented on TS-Assignment/Que4.ts
> +// Bank Account
where is Bank Account class?

2022-09-13 09:34 UTC, rishikesh-dhanawade-emtec requested changes
check comment

2022-09-13 09:58 UTC, Devyani-Chaudhari commented on TS-Assignment/Que4.ts
> +// Bank Account
Done

2022-11-02 13:34 UTC, rishikesh-dhanawade-emtec approved these changes
approved

2022-11-02 13:39 UTC, merged